type Translation = { nav: Record<"home" | "dashboard" | "documents" | "family" | "verification" | "survey" | "action" | "timeline", string>; notice: string; cta: Record<"check" | "how" | "review" | "continue", string>; labels: Record<"synthetic" | "viewDetails" | "confidence" | "evidence" | "backToCase" | "mock", string>; caseStates: Record<"loading" | "notFoundTitle" | "notFoundDetail" | "errorTitle" | "errorDetail" | "retry", string>; verification: Record<"pageTitle" | "pageSubtitle" | "summaryTitle" | "passed" | "potentialIssue" | "insufficientEvidence" | "passDetail" | "potentialIssueDetail" | "insufficientEvidenceDetail" | "whyFlagged" | "comparedRecords" | "recordA" | "recordB" | "source" | "reference" | "notAvailable" | "caution" | "cautionDetail" | "allChecks" | "reviewDifferences" | "allChecksTitle" | "noResultsTitle" | "noResultsDetail" | "overviewLink", string> };
const en: Translation = {
  nav: { home: "Home", dashboard: "My case", documents: "Documents", family: "Family", verification: "Check records", survey: "Survey record", action: "Next step", timeline: "Timeline" },
  notice: "Independent prototype · Synthetic demo data only · Not legal advice or a government service",
  cta: { check: "Check My Land Record", how: "See How It Works", review: "Review survey record", continue: "Continue" },
  labels: { synthetic: "Synthetic demo", viewDetails: "View details", confidence: "Confidence", evidence: "Evidence", backToCase: "Back to my case", mock: "Mock only — nothing will be submitted" },
  caseStates: { loading: "Loading your synthetic case…", notFoundTitle: "Case not found", notFoundDetail: "This synthetic case does not exist. Choose a demo case or create a new one.", errorTitle: "We could not load this section", errorDetail: "Please try again. Your case has not been changed.", retry: "Try again" },
  verification: { pageTitle: "Check your records", pageSubtitle: "BhoomiCheck compares available synthetic records. It does not make legal conclusions.", summaryTitle: "Record comparison summary", passed: "No obvious discrepancy found", potentialIssue: "Possible mismatch found", insufficientEvidence: "Not enough comparable information", passDetail: "No obvious discrepancy was found in the compared records.", potentialIssueDetail: "A possible mismatch was found. Review the records below.", insufficientEvidenceDetail: "Not enough comparable information is available to make this check.", whyFlagged: "Why was this flagged?", comparedRecords: "Compared records", recordA: "Record A", recordB: "Record B", source: "Source", reference: "Comparison reference", notAvailable: "Not available in the compared records", caution: "Important to know", cautionDetail: "A possible mismatch is not proof that a record is incorrect. BhoomiCheck does not establish legal ownership. Verify important decisions against appropriate official records and processes.", allChecks: "All comparison checks", reviewDifferences: "Review the records that differ", allChecksTitle: "Every result, with its comparison reference", noResultsTitle: "No comparison results yet", noResultsDetail: "BhoomiCheck needs comparable synthetic records before it can show a check.", overviewLink: "Review comparisons" }
};

export const copy: Record<"en" | "hi", Translation> = {
  en,
  hi: {
    nav: { home: "होम", dashboard: "मेरा केस", documents: "दस्तावेज़", family: "परिवार", verification: "रिकॉर्ड जाँचें", survey: "सर्वे रिकॉर्ड", action: "अगला कदम", timeline: "समयरेखा" },
    notice: "स्वतंत्र प्रोटोटाइप · केवल सिंथेटिक डेमो डेटा · कानूनी सलाह या सरकारी सेवा नहीं",
    cta: { check: "भूमि रिकॉर्ड जाँचें", how: "कैसे काम करता है", review: "सर्वे रिकॉर्ड देखें", continue: "आगे बढ़ें" },
    labels: { synthetic: "सिंथेटिक डेमो", viewDetails: "विवरण देखें", confidence: "विश्वास", evidence: "साक्ष्य", backToCase: "मेरे केस पर लौटें", mock: "केवल मॉक — कुछ भी जमा नहीं होगा" },
    caseStates: { loading: "आपका सिंथेटिक केस लोड हो रहा है…", notFoundTitle: "केस नहीं मिला", notFoundDetail: "यह सिंथेटिक केस मौजूद नहीं है। डेमो केस चुनें या नया केस बनाएं।", errorTitle: "यह अनुभाग लोड नहीं हो सका", errorDetail: "कृपया पुनः प्रयास करें। आपके केस में कोई बदलाव नहीं हुआ है।", retry: "पुनः प्रयास करें" },
    verification: { pageTitle: "रिकॉर्ड जाँचें", pageSubtitle: "BhoomiCheck उपलब्ध सिंथेटिक रिकॉर्ड की तुलना करता है। यह कानूनी निष्कर्ष नहीं देता।", summaryTitle: "रिकॉर्ड तुलना सारांश", passed: "कोई स्पष्ट अंतर नहीं मिला", potentialIssue: "संभावित अंतर मिला", insufficientEvidence: "तुलना के लिए पर्याप्त जानकारी नहीं", passDetail: "तुलना किए गए रिकॉर्ड में कोई स्पष्ट अंतर नहीं मिला।", potentialIssueDetail: "संभावित अंतर मिला। नीचे दिए रिकॉर्ड देखें।", insufficientEvidenceDetail: "इस जाँच के लिए पर्याप्त तुलनीय जानकारी उपलब्ध नहीं है।", whyFlagged: "इसे क्यों चिह्नित किया गया?", comparedRecords: "तुलना किए गए रिकॉर्ड", recordA: "रिकॉर्ड A", recordB: "रिकॉर्ड B", source: "स्रोत", reference: "तुलना संदर्भ", notAvailable: "तुलना किए गए रिकॉर्ड में उपलब्ध नहीं", caution: "ध्यान रखें", cautionDetail: "संभावित अंतर यह साबित नहीं करता कि कोई रिकॉर्ड गलत है। BhoomiCheck कानूनी स्वामित्व तय नहीं करता। महत्वपूर्ण निर्णयों की जाँच उचित आधिकारिक रिकॉर्ड और प्रक्रियाओं से करें।", allChecks: "सभी तुलना जाँच", reviewDifferences: "अलग रिकॉर्ड की समीक्षा करें", allChecksTitle: "हर परिणाम और उसका तुलना संदर्भ", noResultsTitle: "अभी कोई तुलना परिणाम नहीं", noResultsDetail: "जाँच दिखाने के लिए BhoomiCheck को तुलनीय सिंथेटिक रिकॉर्ड चाहिए।", overviewLink: "तुलना देखें" }
  }
};
export type Locale = keyof typeof copy;
export const t = (locale: Locale = "en") => copy[locale];
