import { DatabaseSync } from "node:sqlite";
import { mkdirSync } from "node:fs";
import { join } from "node:path";
import type { CaseDetail, DocumentItem, FamilyRelationship, LandCase, LandParcel, NextAction, SurveyRecord, TimelineEvent, VerificationItem } from "@/types/case";
import type { CreateCaseInput } from "@/services/case-service";

const databasePath = join(process.cwd(), "data", "bhoomi-check.sqlite");
let database: DatabaseSync | undefined;
function db() { if (!database) { mkdirSync(join(process.cwd(), "data"), { recursive: true }); database = new DatabaseSync(databasePath); database.exec(`PRAGMA foreign_keys = ON; CREATE TABLE IF NOT EXISTS cases (id TEXT PRIMARY KEY, payload TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, synthetic INTEGER NOT NULL); CREATE TABLE IF NOT EXISTS people (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS family_relationships (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS land_parcels (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS documents (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS survey_records (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS verification_results (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS case_actions (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE TABLE IF NOT EXISTS timeline_events (id TEXT PRIMARY KEY, case_id TEXT NOT NULL REFERENCES cases(id), payload TEXT NOT NULL); CREATE INDEX IF NOT EXISTS documents_case_id ON documents(case_id); CREATE INDEX IF NOT EXISTS parcels_case_id ON land_parcels(case_id);`); } return database; }
type Row = { payload: string };
const getMany = <T>(table: string, caseId: string): T[] => db().prepare(`SELECT payload FROM ${table} WHERE case_id = ?`).all(caseId).map((row) => JSON.parse((row as Row).payload) as T);
const getOne = <T>(table: string, caseId: string): T | undefined => getMany<T>(table, caseId)[0];

function seedDetail(id: string, displayName: string, district: string, circle: string, mauza: string, khata: string, khesra: string, area: number): CaseDetail { const personId = `${id}-person`; const landCase: LandCase = { id, nickname: displayName, location: { district, circle, village: mauza }, surveyStage: "Synthetic records ready to review", progress: { done: 3, total: 5 } }; const document: DocumentItem = { id: `${id}-document`, title: "Synthetic legacy land record", kind: "legacy-record", type: "Legacy record", addedLabel: "Seeded synthetic data", state: "extracted", fields: [{ id: `${id}-field`, label: "Khata number", value: khata, confidence: 100, source: "Synthetic seed text" }], sourceText: `MOCK SYNTHETIC DOCUMENT\nKhata: ${khata}\nKhesra: ${khesra}\nArea: ${area} acres`, isSynthetic: true }; return { case: landCase, family: { members: [{ id: personId, name: `Synthetic Holder ${displayName.slice(-3)}`, role: "Recorded person", note: "Synthetic seed data" }], relationships: [] }, landParcels: [{ id: `${id}-parcel`, label: "Synthetic parcel", khata, khesra, area: { value: area, unit: "acres" } }], documents: [document], surveyRecord: { recordedName: `Synthetic Holder ${displayName.slice(-3)}`, khata, khesra, area: { value: area, unit: "acres" }, surveyStage: landCase.surveyStage, mapReference: `DEMO-MAP-${displayName.slice(-3)}` }, verification: [], nextAction: { recommendedTitle: "Review your synthetic document", recommendedDetail: "Inspect the synthetic source text and extracted field.", steps: ["Open the document.", "Review its extracted field."], options: [{ id: "review", title: "Review supporting document", detail: "Read the synthetic record." }] }, timeline: [{ id: `${id}-created`, dateLabel: "Seeded", title: "Synthetic case created", detail: "This demo case contains fictional data only.", status: "current" }] }; }

export class CaseNotFoundError extends Error {}
export class ValidationError extends Error {}
export class CaseApplicationService {
  constructor() { this.seed(); }
  private seed() { const count = db().prepare("SELECT count(*) AS count FROM cases").get() as { count: number }; if (!count.count) { this.persist(seedDetail("demo-family-001", "Demo Case 001", "Demo District", "Demo Circle", "Example Mauza A", "DEMO-128", "DEMO-456", 0.82)); this.persist(seedDetail("demo-family-002", "Demo Case 002", "Sample District", "Sample Circle", "Example Mauza B", "DEMO-902", "DEMO-114", 1.25)); } }
  private persist(detail: CaseDetail) { const now = new Date().toISOString(); const insert = (table: string, id: string, caseId: string, payload: unknown) => db().prepare(`INSERT OR REPLACE INTO ${table} (id, case_id, payload) VALUES (?, ?, ?)`).run(id, caseId, JSON.stringify(payload)); db().prepare("INSERT OR REPLACE INTO cases (id,payload,created_at,updated_at,synthetic) VALUES (?,?,?,?,1)").run(detail.case.id, JSON.stringify(detail.case), now, now); detail.family.members.forEach((item) => insert("people", item.id, detail.case.id, item)); detail.family.relationships.forEach((item) => insert("family_relationships", item.id, detail.case.id, item)); detail.landParcels.forEach((item) => insert("land_parcels", item.id, detail.case.id, item)); detail.documents.forEach((item) => insert("documents", item.id, detail.case.id, item)); if (detail.surveyRecord) insert("survey_records", `${detail.case.id}-survey`, detail.case.id, detail.surveyRecord); detail.verification.forEach((item) => insert("verification_results", item.id, detail.case.id, item)); if (detail.nextAction) insert("case_actions", `${detail.case.id}-action`, detail.case.id, detail.nextAction); detail.timeline.forEach((item) => insert("timeline_events", item.id, detail.case.id, item)); }
  getCaseDetail(caseId: string): CaseDetail | null { const row = db().prepare("SELECT payload FROM cases WHERE id = ?").get(caseId) as Row | undefined; if (!row) return null; const landCase = JSON.parse(row.payload) as LandCase; return { case: landCase, family: { members: getMany("people", caseId), relationships: getMany<FamilyRelationship>("family_relationships", caseId) }, landParcels: getMany<LandParcel>("land_parcels", caseId), documents: getMany<DocumentItem>("documents", caseId), surveyRecord: getOne<SurveyRecord>("survey_records", caseId), verification: getMany<VerificationItem>("verification_results", caseId), nextAction: getOne<NextAction>("case_actions", caseId), timeline: getMany<TimelineEvent>("timeline_events", caseId) }; }
  createCase(input: CreateCaseInput): CaseDetail { if (!input.nickname.trim() || !input.district.trim() || !input.circle.trim() || !input.village.trim() || !/^DEMO-[A-Z0-9-]+$/i.test(input.khata)) throw new ValidationError("Use the required synthetic case fields and a DEMO- Khata number."); const id = `case-${crypto.randomUUID()}`; const detail: CaseDetail = { case: { id, nickname: input.nickname.trim(), location: { district: input.district.trim(), circle: input.circle.trim(), village: input.village.trim() }, surveyStage: "Synthetic case created", progress: { done: 1, total: 5 } }, family: { members: [], relationships: [] }, landParcels: [{ id: `${id}-parcel`, label: "Synthetic parcel", khata: input.khata.trim(), khesra: input.khesra?.trim(), area: { value: 0, unit: "acres" } }], documents: [], verification: [], timeline: [{ id: `${id}-created`, dateLabel: "Today", title: "Case created", detail: "Your synthetic case is ready for its first document.", status: "current" }] }; this.persist(detail); return detail; }
}
export const caseApplicationService = new CaseApplicationService();
