import type { CaseDetail, DocumentItem, FamilyRelationship, LandCase, LandParcel, NextAction, SurveyRecord, TimelineEvent, VerificationItem } from "@/types/case";
import type { CreateCaseInput } from "@/services/case-service";
import { PROTOTYPE_MODE, isValidSyntheticCaseInput } from "@/server/prototype-mode";
import { getDatabase, type SqlStatement } from "@/server/database";

type Row = { payload: string };

function seedDetail(id: string, displayName: string, district: string, circle: string, mauza: string, khata: string, khesra: string, area: number): CaseDetail { const personId = `${id}-person`; const landCase: LandCase = { id, nickname: displayName, location: { district, circle, village: mauza }, surveyStage: "Synthetic records ready to review", progress: { done: 3, total: 5 } }; const document: DocumentItem = { id: `${id}-document`, title: "Synthetic legacy land record", kind: "legacy-record", type: "Legacy record", addedLabel: "Seeded synthetic data", state: "extracted", fields: [{ id: `${id}-field`, label: "Khata number", value: khata, confidence: 100, source: "Synthetic seed text" }], sourceText: `MOCK SYNTHETIC DOCUMENT\nKhata: ${khata}\nKhesra: ${khesra}\nArea: ${area} acres`, isSynthetic: true }; return { case: landCase, family: { members: [{ id: personId, name: `Synthetic Holder ${displayName.slice(-3)}`, role: "Recorded person", note: "Synthetic seed data" }], relationships: [] }, landParcels: [{ id: `${id}-parcel`, label: "Synthetic parcel", khata, khesra, area: { value: area, unit: "acres" } }], documents: [document], surveyRecord: { recordedName: `Synthetic Holder ${displayName.slice(-3)}`, khata, khesra, area: { value: area, unit: "acres" }, surveyStage: landCase.surveyStage, mapReference: `DEMO-MAP-${displayName.slice(-3)}` }, verification: [], nextAction: { recommendedTitle: "Review your synthetic document", recommendedDetail: "Inspect the synthetic source text and extracted field.", steps: ["Open the document.", "Review its extracted field."], options: [{ id: "review", title: "Review supporting document", detail: "Read the synthetic record." }] }, timeline: [{ id: `${id}-created`, dateLabel: "Seeded", title: "Synthetic case created", detail: "This demo case contains fictional data only.", status: "current" }] }; }

const seededCase = (caseId: string) => caseId === "demo-family-001" ? seedDetail("demo-family-001", "Demo Case 001", "Demo District", "Demo Circle", "Example Mauza A", "DEMO-128", "DEMO-456", 0.82) : caseId === "demo-family-002" ? seedDetail("demo-family-002", "Demo Case 002", "Sample District", "Sample Circle", "Example Mauza B", "DEMO-902", "DEMO-114", 1.25) : null;

export class CaseNotFoundError extends Error {}
export class ValidationError extends Error {}
export class CaseApplicationService {
  private seeded = false;
  private async ready() { const database = getDatabase(); await database.initialize(); if (!this.seeded) { for (const id of ["demo-family-001", "demo-family-002"] as const) { const existing = await database.query<Row>({ sql: "SELECT payload FROM cases WHERE id = ?", params: [id] }); if (!existing.length) await this.persist(seededCase(id)!); } this.seeded = true; } return database; }
  private async persist(detail: CaseDetail) { const now = new Date().toISOString(); const insert = (table: string, id: string, payload: unknown): SqlStatement => ({ sql: `INSERT INTO ${table} (id,case_id,payload) VALUES (?,?,?) ON CONFLICT (id) DO UPDATE SET case_id = EXCLUDED.case_id, payload = EXCLUDED.payload`, params: [id, detail.case.id, JSON.stringify(payload)] }); const statements: SqlStatement[] = [{ sql: "INSERT INTO cases (id,payload,created_at,updated_at,synthetic) VALUES (?,?,?,?,?) ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload, updated_at = EXCLUDED.updated_at", params: [detail.case.id, JSON.stringify(detail.case), now, now, true] }]; detail.family.members.forEach((item) => statements.push(insert("people", item.id, item))); detail.family.relationships.forEach((item) => statements.push(insert("family_relationships", item.id, item))); detail.landParcels.forEach((item) => statements.push(insert("land_parcels", item.id, item))); detail.documents.forEach((item) => statements.push(insert("documents", item.id, item))); if (detail.surveyRecord) statements.push(insert("survey_records", `${detail.case.id}-survey`, detail.surveyRecord)); detail.verification.forEach((item) => statements.push(insert("verification_results", item.id, item))); if (detail.nextAction) statements.push(insert("case_actions", `${detail.case.id}-action`, detail.nextAction)); detail.timeline.forEach((item) => statements.push(insert("timeline_events", item.id, item))); await getDatabase().transaction(statements); }
  async getCaseDetail(caseId: string): Promise<CaseDetail | null> { const database = await this.ready(); const row = (await database.query<Row>({ sql: "SELECT payload FROM cases WHERE id = ?", params: [caseId] }))[0]; if (!row) return null; const many = async <T>(table: string) => (await database.query<Row>({ sql: `SELECT payload FROM ${table} WHERE case_id = ?`, params: [caseId] })).map((item) => JSON.parse(item.payload) as T); const landCase = JSON.parse(row.payload) as LandCase; const [members, relationships, landParcels, documents, surveys, verification, actions, timeline] = await Promise.all([many<CaseDetail["family"]["members"][number]>("people"), many<FamilyRelationship>("family_relationships"), many<LandParcel>("land_parcels"), many<DocumentItem>("documents"), many<SurveyRecord>("survey_records"), many<VerificationItem>("verification_results"), many<NextAction>("case_actions"), many<TimelineEvent>("timeline_events")]); return { case: landCase, family: { members, relationships }, landParcels, documents, surveyRecord: surveys[0], verification, nextAction: actions[0], timeline }; }
  async resetSeedCase(caseId: string): Promise<CaseDetail | null> { const detail = seededCase(caseId); if (!detail) return null; const database = await this.ready(); const tables = ["document_extractions", "review_packets", "verification_results", "timeline_events", "case_actions", "survey_records", "documents", "land_parcels", "family_relationships", "people"]; await database.transaction([...tables.map((table) => ({ sql: `DELETE FROM ${table} WHERE case_id = ?`, params: [caseId] })), { sql: "DELETE FROM cases WHERE id = ?", params: [caseId] }]); await this.persist(detail); return detail; }
  async createCase(input: CreateCaseInput): Promise<CaseDetail> { if (!isValidSyntheticCaseInput(input)) throw new ValidationError("Use clearly labelled synthetic case details and DEMO- identifiers."); await this.ready(); const id = `demo-case-${crypto.randomUUID()}`; const detail: CaseDetail = { case: { id, nickname: input.nickname.trim(), location: { district: input.district.trim(), circle: input.circle.trim(), village: input.village.trim() }, surveyStage: "Synthetic case created", progress: { done: 1, total: 5 } }, family: { members: [], relationships: [] }, landParcels: [{ id: `${id}-parcel`, label: "Synthetic parcel", khata: input.khata.trim(), khesra: input.khesra?.trim(), area: { value: 0, unit: "acres" } }], documents: [], verification: [], timeline: [{ id: `${id}-created`, dateLabel: "Today", title: "Case created", detail: `Your ${PROTOTYPE_MODE} case is ready for its first document.`, status: "current" }] }; await this.persist(detail); return detail; }
}
export const caseApplicationService = new CaseApplicationService();
