import type { DocumentItem, DocumentKind } from "@/types/case";
import type { PreparedDocument } from "@/server/extraction";
import { syntheticDocumentFixtures } from "@/fixtures/synthetic-documents";
import { SyntheticDocumentProcessor, documentFromFixture } from "@/services/document-processing";
import { caseApplicationService } from "@/server/case-application-service";
import { isApprovedSyntheticFixture } from "@/server/prototype-mode";
import { getDatabase } from "@/server/database";

const notice = "Synthetic demo document — not an official government record.";
const hero = [["historical", "Historical Khatiyan-style record", "legacy-record", "Khata: DEMO-128\nKhesra: DEMO-456\nRecorded holder: Synthetic Elder 001\nArea: 1.20 acre\nMauza: Example Mauza A"], ["genealogy", "Genealogy / Vanshavali-style record", "family-note", "Synthetic Elder 001 → Synthetic Child A 001\nSynthetic Elder 001 → Synthetic Child B 001\nFamily member under review: Synthetic Child B 001"], ["current", "Current Jamabandi-like record", "legacy-record", "Khata: DEMO-128\nKhesra: DEMO-456\nRecorded holder: Synthetic Child A 001\nArea: 1.20 acre"], ["support", "Synthetic inheritance support document", "family-note", "Recorded family context: Synthetic Child A 001 and Synthetic Child B 001\nArea reference: 1.20 acre"], ["survey", "Synthetic Khanapuri Parcha-style record", "survey-record", "Khata: DEMO-128\nKhesra: DEMO-456\nRecorded holder: Synthetic Child A 001\nArea: 1.02 acre\nMap reference: DEMO-MAP-001"], ["map", "Simplified synthetic parcel sketch", "survey-record", "Parcel sketch: DEMO-128 / DEMO-456\nArea label: 1.20 acre\nMap reference: DEMO-MAP-001"]] as const;
const control = [["control-current", "Control synthetic land record", "legacy-record", "Khata: DEMO-902\nKhesra: DEMO-114\nRecorded holder: Synthetic Holder 002\nArea: 1.25 acre"], ["control-survey", "Control synthetic survey record", "survey-record", "Khata: DEMO-902\nKhesra: DEMO-114\nRecorded holder: Synthetic Holder 002\nArea: 1.25 acre\nMap reference: DEMO-MAP-002"]] as const;

export class DocumentApplicationService {
  async ensureSeedDocuments() { const db = getDatabase(); await db.initialize(); for (const [caseId, key, title, kind, text] of [...hero.map((item) => ["demo-family-001", ...item] as const), ...control.map((item) => ["demo-family-002", ...item] as const)]) { const id = `${caseId}-${key}`; if ((await db.query<{ id: string }>({ sql: "SELECT id FROM documents WHERE id = ?", params: [id] })).length && key !== "genealogy") continue; const payload: DocumentItem = { id, title, kind: kind as DocumentKind, type: title, addedLabel: "Seeded synthetic document", state: "extracted", fields: [], sourceText: `${notice}\n\n${text}`, isSynthetic: true }; await db.execute({ sql: "INSERT INTO documents (id,case_id,payload) VALUES (?,?,?) ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload", params: [id, caseId, JSON.stringify(payload)] }); } }
  async list(caseId: string) { await this.ensureSeedDocuments(); return (await getDatabase().query<{ payload: string }>({ sql: "SELECT payload FROM documents WHERE case_id = ?", params: [caseId] })).map((row) => JSON.parse(row.payload) as DocumentItem); }
  async get(caseId: string, documentId: string) { return (await this.list(caseId)).find((item) => item.id === documentId) ?? null; }
  listSyntheticFixtures() { return syntheticDocumentFixtures; }
  async attachSyntheticFixture(caseId: string, fixtureId: string) { if (!await caseApplicationService.getCaseDetail(caseId)) return null; const fixture = isApprovedSyntheticFixture(syntheticDocumentFixtures, fixtureId); if (!fixture) return null; const existing = await this.get(caseId, `${caseId}-${fixture.id}`); if (existing) return existing; const document = new SyntheticDocumentProcessor().process(documentFromFixture(caseId, fixture)); await getDatabase().execute({ sql: "INSERT INTO documents (id,case_id,payload) VALUES (?,?,?)", params: [document.id, caseId, JSON.stringify(document)] }); return document; }
  async prepare(caseId: string, documentId: string): Promise<PreparedDocument | null> { const document = await this.get(caseId, documentId); return document?.isSynthetic ? { documentId, caseId, documentType: document.kind, text: document.sourceText, metadata: { filename: `${document.id}.txt`, mimeType: "text/plain", section: "synthetic-content" }, synthetic: true } : null; }
}
export const documentApplicationService = new DocumentApplicationService();
