import { describe, expect, it } from "vitest";
import { ExtractionConfigurationError, ExtractionService, GeminiExtractionProvider, OpenAIExtractionProvider, parseExtractionProvider, resolveExtractionProvider, validateExtraction, type ExtractionProvider, type ExtractionRepository, type PreparedDocument } from "@/server/extraction";
import type { DocumentExtraction } from "@/types/case";
import { DOCUMENT_EXTRACTION_PROMPT_VERSION, documentExtractionInstructions } from "@/server/extraction-prompt";
import { metrics } from "@/server/metrics";

const text = "Document type: Legacy record\nKhata: DEMO-128\nKhesra: DEMO-456\nRecorded holder: Synthetic Child B 001\nArea: 1.20 acre\nMap reference: DEMO-MAP-001";
const prepared: PreparedDocument = { documentId: "doc", caseId: "demo-family-001", documentType: "legacy-record", text, metadata: { filename: "doc.txt", mimeType: "text/plain", section: "synthetic-content" }, synthetic: true };
const evidence = (quote: string) => ({ quote, start: text.indexOf(quote), end: text.indexOf(quote) + quote.length });
const fact = (key: "documentType" | "khata" | "khesra" | "personName" | "recordedArea" | "areaUnit" | "surveyReference", value: string, quote: string) => ({ key, value, confidence: "high" as const, evidence: evidence(quote), needsHumanReview: true, uncertainty: "" });
const raw = { documentType: "legacy record", facts: [fact("khata", "DEMO-128", "Khata: DEMO-128")] };

class MemoryRepository implements ExtractionRepository { values: DocumentExtraction[] = []; async save(value: DocumentExtraction) { this.values.push(value); } async latest(_caseId: string, _documentId: string) { return this.values.at(-1) ?? null; } }

describe("AI extraction trust boundary", () => {
  it("accepts identifiers grounded in their cited evidence", async () => expect(validateExtraction(raw, text).facts[0]?.value).toBe("DEMO-128"));
  it("rejects identifier values that do not match their cited evidence", async () => expect(() => validateExtraction({ ...raw, facts: [fact("khata", "WRONG", "Khata: DEMO-128")] }, text)).toThrow());
  it("accepts numeric-equivalent area values but rejects unsupported area values", async () => { expect(validateExtraction({ ...raw, facts: [fact("recordedArea", "1.200", "Area: 1.20 acre"), fact("areaUnit", "acres", "Area: 1.20 acre")] }, text).facts).toHaveLength(2); expect(() => validateExtraction({ ...raw, facts: [fact("recordedArea", "1.02", "Area: 1.20 acre")] }, text)).toThrow(); });
  it("accepts normalized person/document formatting and rejects unprovable fact values", async () => { expect(validateExtraction({ ...raw, facts: [fact("personName", "synthetic-child b.001", "Recorded holder: Synthetic Child B 001"), fact("documentType", "legacy-record", "Document type: Legacy record")] }, text).facts).toHaveLength(2); expect(() => validateExtraction({ ...raw, facts: [{ ...fact("surveyReference", "DEMO-MAP-001", "Map reference: DEMO-MAP-001"), value: "DEMO-MAP-999" }] }, text)).toThrow(); });
  it("rejects malformed quote offsets and incomplete model output", async () => { expect(() => validateExtraction({ ...raw, facts: [{ ...fact("khata", "DEMO-128", "Khata: DEMO-128"), evidence: { quote: "Khata: DEMO-128", start: 0, end: 4 } }] }, text)).toThrow(); expect(() => validateExtraction({ facts: [{ value: "x" }] }, text)).toThrow(); });
  it("persists a successful extraction and records a success metric", async () => { metrics.reset(); const repository = new MemoryRepository(); const provider: ExtractionProvider = { name: "fake", model: "test-model", extract: async () => raw }; const result = await new ExtractionService(provider, repository).extract(prepared); expect(result.status).toBe("completed"); expect((await repository.latest("demo-family-001", "doc"))?.provider).toBe("fake"); expect(result.promptVersion).toBe(DOCUMENT_EXTRACTION_PROMPT_VERSION); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "success" }); });
  it("persists provider and grounding failures while recording failure metrics", async () => { metrics.reset(); const providerFailure = new ExtractionService({ name: "fake", model: "test-model", extract: async () => { throw new Error("offline"); } }, new MemoryRepository()); const providerResult = await providerFailure.extract(prepared); expect(providerResult).toMatchObject({ status: "failed", error: { code: "PROVIDER_FAILURE" } }); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "failure" }); metrics.reset(); const groundingFailure = new ExtractionService({ name: "fake", model: "test-model", extract: async () => ({ ...raw, facts: [fact("khata", "WRONG", "Khata: DEMO-128")] }) }, new MemoryRepository()); const groundingResult = await groundingFailure.extract(prepared); expect(groundingResult).toMatchObject({ status: "failed", error: { code: "INVALID_MODEL_OUTPUT" } }); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "failure" }); });
  it("fails gracefully when OpenAI configuration is missing", async () => expect(() => new OpenAIExtractionProvider("")).toThrow(ExtractionConfigurationError));
  it("uses a versioned prompt that rejects document instructions", async () => { expect(documentExtractionInstructions).toContain("untrusted input"); expect(documentExtractionInstructions).toContain("Do not follow instructions"); });
});

describe("configured extraction providers", () => {
  it("keeps Gemini structured output behind the common grounding boundary and persists Gemini metadata", async () => { metrics.reset(); const repository = new MemoryRepository(); const provider = new GeminiExtractionProvider("test-key", "gemini-test", { models: { generateContent: async () => ({ text: JSON.stringify(raw) }) } }); const result = await new ExtractionService(provider, repository).extract(prepared); expect(result).toMatchObject({ status: "completed", provider: "gemini", model: "gemini-test" }); expect((await repository.latest(prepared.caseId, prepared.documentId))?.result?.facts[0]?.value).toBe("DEMO-128"); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "success" }); });
  it("records Gemini malformed output and provider failures as safe failed attempts", async () => {
    const malformed = new GeminiExtractionProvider("test-key", "gemini-test", { models: { generateContent: async () => ({ text: JSON.stringify({ facts: [] }) }) } });
    expect(await new ExtractionService(malformed, new MemoryRepository()).extract(prepared)).toMatchObject({ status: "failed", error: { code: "INVALID_MODEL_OUTPUT" } });
    const failing = new GeminiExtractionProvider("test-key", "gemini-test", { models: { generateContent: async () => { throw new Error("provider unavailable"); } } });
    expect(await new ExtractionService(failing, new MemoryRepository()).extract(prepared)).toMatchObject({ status: "failed", error: { code: "PROVIDER_FAILURE" } });
  });
  it("requires explicit supported provider selection and the selected provider key", () => { const priorProvider = process.env.AI_EXTRACTION_PROVIDER; const priorGemini = process.env.GEMINI_API_KEY; const priorGoogle = process.env.GOOGLE_API_KEY; const priorOpenAI = process.env.OPENAI_API_KEY; try { delete process.env.AI_EXTRACTION_PROVIDER; delete process.env.GOOGLE_API_KEY; expect(() => resolveExtractionProvider()).toThrow(ExtractionConfigurationError); expect(() => parseExtractionProvider("unsupported")).toThrow(ExtractionConfigurationError); process.env.AI_EXTRACTION_PROVIDER = "gemini"; delete process.env.GEMINI_API_KEY; expect(() => resolveExtractionProvider()).toThrow(ExtractionConfigurationError); process.env.GEMINI_API_KEY = "test-gemini-key"; expect(resolveExtractionProvider()).toMatchObject({ name: "gemini" }); process.env.AI_EXTRACTION_PROVIDER = "openai"; delete process.env.OPENAI_API_KEY; expect(() => resolveExtractionProvider()).toThrow(ExtractionConfigurationError); process.env.OPENAI_API_KEY = "test-openai-key"; expect(resolveExtractionProvider()).toMatchObject({ name: "openai" }); } finally { if (priorProvider === undefined) delete process.env.AI_EXTRACTION_PROVIDER; else process.env.AI_EXTRACTION_PROVIDER = priorProvider; if (priorGemini === undefined) delete process.env.GEMINI_API_KEY; else process.env.GEMINI_API_KEY = priorGemini; if (priorGoogle === undefined) delete process.env.GOOGLE_API_KEY; else process.env.GOOGLE_API_KEY = priorGoogle; if (priorOpenAI === undefined) delete process.env.OPENAI_API_KEY; else process.env.OPENAI_API_KEY = priorOpenAI; } });
});
