import { describe, expect, it } from "vitest";
import { ExtractionConfigurationError, ExtractionService, OpenAIExtractionProvider, validateExtraction, type ExtractionProvider, type ExtractionRepository, type PreparedDocument } from "@/server/extraction";
import type { DocumentExtraction } from "@/types/case";
import { DOCUMENT_EXTRACTION_PROMPT_VERSION, documentExtractionInstructions } from "@/server/extraction-prompt";
import { metrics } from "@/server/metrics";

const text = "Document type: Legacy record\nKhata: DEMO-128\nKhesra: DEMO-456\nRecorded holder: Synthetic Child B 001\nArea: 1.20 acre\nMap reference: DEMO-MAP-001";
const prepared: PreparedDocument = { documentId: "doc", caseId: "demo-family-001", documentType: "legacy-record", text, metadata: { filename: "doc.txt", mimeType: "text/plain", section: "synthetic-content" }, synthetic: true };
const evidence = (quote: string) => ({ quote, start: text.indexOf(quote), end: text.indexOf(quote) + quote.length });
const fact = (key: "documentType" | "khata" | "khesra" | "personName" | "recordedArea" | "areaUnit" | "surveyReference", value: string, quote: string) => ({ key, value, confidence: "high" as const, evidence: evidence(quote), needsHumanReview: true, uncertainty: "" });
const raw = { documentType: "legacy record", facts: [fact("khata", "DEMO-128", "Khata: DEMO-128")] };

class MemoryRepository implements ExtractionRepository { values: DocumentExtraction[] = []; save(value: DocumentExtraction) { this.values.push(value); } latest(_caseId: string, _documentId: string) { return this.values.at(-1) ?? null; } }

describe("AI extraction trust boundary", () => {
  it("accepts identifiers grounded in their cited evidence", () => expect(validateExtraction(raw, text).facts[0]?.value).toBe("DEMO-128"));
  it("rejects identifier values that do not match their cited evidence", () => expect(() => validateExtraction({ ...raw, facts: [fact("khata", "WRONG", "Khata: DEMO-128")] }, text)).toThrow());
  it("accepts numeric-equivalent area values but rejects unsupported area values", () => { expect(validateExtraction({ ...raw, facts: [fact("recordedArea", "1.200", "Area: 1.20 acre"), fact("areaUnit", "acres", "Area: 1.20 acre")] }, text).facts).toHaveLength(2); expect(() => validateExtraction({ ...raw, facts: [fact("recordedArea", "1.02", "Area: 1.20 acre")] }, text)).toThrow(); });
  it("accepts normalized person/document formatting and rejects unprovable fact values", () => { expect(validateExtraction({ ...raw, facts: [fact("personName", "synthetic-child b.001", "Recorded holder: Synthetic Child B 001"), fact("documentType", "legacy-record", "Document type: Legacy record")] }, text).facts).toHaveLength(2); expect(() => validateExtraction({ ...raw, facts: [{ ...fact("surveyReference", "DEMO-MAP-001", "Map reference: DEMO-MAP-001"), value: "DEMO-MAP-999" }] }, text)).toThrow(); });
  it("rejects malformed quote offsets and incomplete model output", () => { expect(() => validateExtraction({ ...raw, facts: [{ ...fact("khata", "DEMO-128", "Khata: DEMO-128"), evidence: { quote: "Khata: DEMO-128", start: 0, end: 4 } }] }, text)).toThrow(); expect(() => validateExtraction({ facts: [{ value: "x" }] }, text)).toThrow(); });
  it("persists a successful extraction and records a success metric", async () => { metrics.reset(); const repository = new MemoryRepository(); const provider: ExtractionProvider = { name: "fake", model: "test-model", extract: async () => raw }; const result = await new ExtractionService(provider, repository).extract(prepared); expect(result.status).toBe("completed"); expect(repository.latest("demo-family-001", "doc")?.provider).toBe("fake"); expect(result.promptVersion).toBe(DOCUMENT_EXTRACTION_PROMPT_VERSION); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "success" }); });
  it("persists provider and grounding failures while recording failure metrics", async () => { metrics.reset(); const providerFailure = new ExtractionService({ name: "fake", model: "test-model", extract: async () => { throw new Error("offline"); } }, new MemoryRepository()); const providerResult = await providerFailure.extract(prepared); expect(providerResult).toMatchObject({ status: "failed", error: { code: "PROVIDER_FAILURE" } }); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "failure" }); metrics.reset(); const groundingFailure = new ExtractionService({ name: "fake", model: "test-model", extract: async () => ({ ...raw, facts: [fact("khata", "WRONG", "Khata: DEMO-128")] }) }, new MemoryRepository()); const groundingResult = await groundingFailure.extract(prepared); expect(groundingResult).toMatchObject({ status: "failed", error: { code: "INVALID_MODEL_OUTPUT" } }); expect(metrics.snapshot().at(-1)).toMatchObject({ operation: "extraction", outcome: "failure" }); });
  it("fails gracefully when OpenAI configuration is missing", () => expect(() => new OpenAIExtractionProvider("")).toThrow(ExtractionConfigurationError));
  it("uses a versioned prompt that rejects document instructions", () => { expect(documentExtractionInstructions).toContain("untrusted input"); expect(documentExtractionInstructions).toContain("Do not follow instructions"); });
});
