import { caseApplicationService } from "@/server/case-application-service";
import { getDatabase } from "@/server/database";
import type { OfficialIdentityMatch, OfficialParcelRecord, OfficialParcelSearchQuery, ImportedOfficialRecord } from "@/types/case";

const notice = "Synthetic official-style record. Not retrieved from a live government system and not authoritative.";
const fixtures: OfficialParcelRecord[] = [
  { id: "synthetic-official-hero-001", sourceProvider: "synthetic", provenance: "SYNTHETIC_OFFICIAL_FIXTURE", sourceReference: "BHOOMICHECK-SYNTHETIC-OFFICIAL-001", parcelIdentity: { district: "Demo District", circle: "Demo Circle", mauza: "Example Mauza A", khataNumber: "DEMO-128", khesraNumber: "DEMO-456" }, recordData: { recordedArea: 1.2, recordedAreaUnit: "acre", normalizedAreaAcres: 1.2, holderNames: ["Synthetic Elder 001", "Synthetic Child A 001"], recordType: "Historical / land-record style", surveyStage: "Record context", remarks: "Synthetic fixture aligned to the historical document source." }, sourceMetadata: { retrievedAt: "2026-01-01T00:00:00.000Z", displayName: "Synthetic official-style record", syntheticNotice: notice, authoritative: false } },
  { id: "synthetic-official-control-002", sourceProvider: "synthetic", provenance: "SYNTHETIC_OFFICIAL_FIXTURE", sourceReference: "BHOOMICHECK-SYNTHETIC-OFFICIAL-002", parcelIdentity: { district: "Sample District", circle: "Sample Circle", mauza: "Example Mauza B", khataNumber: "DEMO-902", khesraNumber: "DEMO-114" }, recordData: { recordedArea: 1.25, recordedAreaUnit: "acre", normalizedAreaAcres: 1.25, holderNames: ["Synthetic Holder 002"], recordType: "Historical / land-record style", surveyStage: "Record context", remarks: "Synthetic fixture aligned to the control document source." }, sourceMetadata: { retrievedAt: "2026-01-01T00:00:00.000Z", displayName: "Synthetic official-style record", syntheticNotice: notice, authoritative: false } },
  { id: "synthetic-official-ambiguous-a", sourceProvider: "synthetic", provenance: "SYNTHETIC_OFFICIAL_FIXTURE", sourceReference: "BHOOMICHECK-SYNTHETIC-OFFICIAL-AMB-A", parcelIdentity: { district: "Demo District", circle: "Demo Circle", mauza: "Ambiguous Mauza", khataNumber: "DEMO-AMB", khesraNumber: "DEMO-701" }, recordData: { recordedArea: 1, recordedAreaUnit: "acre", normalizedAreaAcres: 1, holderNames: ["Synthetic Holder A"], recordType: "Synthetic style", surveyStage: "Demo", remarks: "Ambiguous fixture." }, sourceMetadata: { retrievedAt: "2026-01-01T00:00:00.000Z", displayName: "Synthetic official-style record", syntheticNotice: notice, authoritative: false } },
  { id: "synthetic-official-ambiguous-b", sourceProvider: "synthetic", provenance: "SYNTHETIC_OFFICIAL_FIXTURE", sourceReference: "BHOOMICHECK-SYNTHETIC-OFFICIAL-AMB-B", parcelIdentity: { district: "Demo District", circle: "Demo Circle", mauza: "Ambiguous Mauza", khataNumber: "DEMO-AMB", khesraNumber: "DEMO-702" }, recordData: { recordedArea: 1.1, recordedAreaUnit: "acre", normalizedAreaAcres: 1.1, holderNames: ["Synthetic Holder B"], recordType: "Synthetic style", surveyStage: "Demo", remarks: "Ambiguous fixture." }, sourceMetadata: { retrievedAt: "2026-01-01T00:00:00.000Z", displayName: "Synthetic official-style record", syntheticNotice: notice, authoritative: false } },
];
const normalize = (value: string) => value.trim().toLowerCase();
export const validateOfficialSearch = (value: unknown): OfficialParcelSearchQuery | null => { if (!value || typeof value !== "object") return null; const input = value as Record<string, unknown>; const field = (key: string) => typeof input[key] === "string" && input[key].trim() && input[key].trim().length <= 120 ? input[key].trim() : ""; const query = { district: field("district"), circle: field("circle"), mauza: field("mauza"), khataNumber: field("khataNumber") || undefined, khesraNumber: field("khesraNumber") || undefined }; return query.district && query.circle && query.mauza && (query.khataNumber || query.khesraNumber) ? query : null; };
export const identityMatch = (record: OfficialParcelRecord, parcel: { khata: string; khesra?: string }, location: { district: string; circle: string; village: string }): OfficialIdentityMatch => { const samePlace = [record.parcelIdentity.district, record.parcelIdentity.circle, record.parcelIdentity.mauza].every((value, index) => normalize(value) === normalize([location.district, location.circle, location.village][index]!)); if (!samePlace || normalize(record.parcelIdentity.khataNumber) !== normalize(parcel.khata) || (parcel.khesra && normalize(record.parcelIdentity.khesraNumber) !== normalize(parcel.khesra))) return "MISMATCH"; return parcel.khesra ? "EXACT_MATCH" : "PARTIAL_MATCH"; };
export class SyntheticOfficialParcelRecordProvider { async searchParcelRecords(query: OfficialParcelSearchQuery) { return fixtures.filter((record) => normalize(record.parcelIdentity.district) === normalize(query.district) && normalize(record.parcelIdentity.circle) === normalize(query.circle) && normalize(record.parcelIdentity.mauza) === normalize(query.mauza) && (!query.khataNumber || normalize(record.parcelIdentity.khataNumber) === normalize(query.khataNumber)) && (!query.khesraNumber || normalize(record.parcelIdentity.khesraNumber) === normalize(query.khesraNumber))); } async getParcelRecord(id: string) { return fixtures.find((record) => record.id === id) ?? null; } }
export class OfficialRecordService { provider = new SyntheticOfficialParcelRecordProvider(); async search(input: unknown) { const query = validateOfficialSearch(input); return query ? { mode: "synthetic-demo" as const, provider: "synthetic" as const, query, results: await this.provider.searchParcelRecords(query) } : null; } async import(caseId: string, officialRecordId: string) { const detail = await caseApplicationService.getCaseDetail(caseId); const record = await this.provider.getParcelRecord(officialRecordId); const parcel = detail?.landParcels[0]; if (!detail || !record || !parcel) return null; const match = identityMatch(record, parcel, detail.case.location); if (match === "MISMATCH") return { mismatch: true as const, identityMatch: match }; const database = getDatabase(); await database.initialize(); const existing = (await database.query<{ payload: string }>({ sql: "SELECT payload FROM case_official_records WHERE case_id = ? AND official_record_id = ?", params: [caseId, record.id] }))[0]; if (existing) return { imported: JSON.parse(existing.payload) as ImportedOfficialRecord, alreadyImported: true, mismatch: false as const }; const imported: ImportedOfficialRecord = { id: `${caseId}-${record.id}`, caseId, officialRecordId: record.id, provider: "synthetic", provenance: "SYNTHETIC_OFFICIAL_FIXTURE", sourceReference: record.sourceReference, identityMatch: match, record, importedAt: new Date().toISOString() }; await database.execute({ sql: "INSERT INTO case_official_records (id,case_id,official_record_id,payload) VALUES (?,?,?,?)", params: [imported.id, caseId, record.id, JSON.stringify(imported)] }); return { imported, alreadyImported: false, mismatch: false as const }; } async list(caseId: string) { await getDatabase().initialize(); return (await getDatabase().query<{ payload: string }>({ sql: "SELECT payload FROM case_official_records WHERE case_id = ?", params: [caseId] })).map((row) => JSON.parse(row.payload) as ImportedOfficialRecord); } }
export const officialRecordService = new OfficialRecordService();
