import { DatabaseSync } from "node:sqlite";
import { join } from "node:path";
import { caseApplicationService } from "@/server/case-application-service";
import { documentApplicationService } from "@/server/document-application-service";
import { verificationService } from "@/server/verification-service";
import type { ReviewPacket } from "@/types/case";
const path = join(process.cwd(), "data", "bhoomi-check.sqlite");
const open = () => { const db = new DatabaseSync(path); db.exec("CREATE TABLE IF NOT EXISTS review_packets (id TEXT PRIMARY KEY, case_id TEXT NOT NULL, payload TEXT NOT NULL); CREATE INDEX IF NOT EXISTS packets_case_id ON review_packets(case_id);"); return db; };
export class ReviewPacketService {
  list(caseId: string) { const db = open(); const rows = db.prepare("SELECT payload FROM review_packets WHERE case_id = ?").all(caseId) as { payload: string }[]; db.close(); return rows.map((row) => JSON.parse(row.payload) as ReviewPacket).sort((left, right) => left.createdAt.localeCompare(right.createdAt)); }
  get(caseId: string, packetId: string) { return this.list(caseId).find((packet) => packet.id === packetId) ?? null; }
  create(caseId: string, verificationResultId: string) { const detail = caseApplicationService.getCaseDetail(caseId); if (!detail) throw new Error("CASE_NOT_FOUND"); const finding = verificationService.run(caseId)?.find((item) => item.id === verificationResultId); if (!finding || finding.outcome !== "POTENTIAL_ISSUE") throw new Error("INELIGIBLE_VERIFICATION_RESULT"); const existing = this.list(caseId).find((packet) => packet.relatedVerificationResultId === finding.id); if (existing) return existing; const parcel = detail.landParcels[0]; const now = new Date().toISOString(); const packet: ReviewPacket = { id: crypto.randomUUID(), caseId, relatedVerificationResultId: finding.id, issueCategory: finding.ruleId, district: detail.case.location.district, circle: detail.case.location.circle, mauza: detail.case.location.village, khata: parcel?.khata || "", khesra: parcel?.khesra, comparedValues: { expected: finding.expectedValue, observed: finding.observedValue }, supportingDocumentIds: finding.sourceDocumentIds.filter((id) => Boolean(documentApplicationService.get(caseId, id))), sourceVerificationResultIds: [finding.id], issueSummary: finding.detail, citizenNotes: "", requestedReviewText: "Please review the synthetic records listed in this draft and clarify the difference shown above.", status: "DRAFT", createdAt: now, updatedAt: now }; this.save(packet); this.timeline(packet, "Review packet created", "A synthetic review packet draft was created."); return packet; }
  update(caseId: string, packetId: string, input: { citizenNotes?: string; requestedReviewText?: string; status?: "READY_FOR_REVIEW" }) { const packet = this.get(caseId, packetId); if (!packet) throw new Error("PACKET_NOT_FOUND"); if (packet.status === "READY_FOR_REVIEW") { if (input.citizenNotes !== undefined || input.requestedReviewText !== undefined) throw new Error("PACKET_LOCKED"); return packet; } const next = { ...packet, citizenNotes: input.citizenNotes ?? packet.citizenNotes, requestedReviewText: input.requestedReviewText ?? packet.requestedReviewText, status: input.status === "READY_FOR_REVIEW" ? "READY_FOR_REVIEW" as const : packet.status, updatedAt: new Date().toISOString() }; this.save(next); if (next.status === "READY_FOR_REVIEW") this.timeline(next, "Packet prepared for review", "This synthetic packet was marked ready for review; it was not submitted."); return next; }
  private save(packet: ReviewPacket) { const db = open(); db.prepare("INSERT OR REPLACE INTO review_packets (id,case_id,payload) VALUES (?,?,?)").run(packet.id, packet.caseId, JSON.stringify(packet)); db.close(); }
  private timeline(packet: ReviewPacket, title: string, detail: string) { const db = open(); const id = `${packet.id}-${title.includes("ready") ? "ready" : "created"}`; const exists = db.prepare("SELECT id FROM timeline_events WHERE id = ?").get(id); if (!exists) db.prepare("INSERT INTO timeline_events (id,case_id,payload) VALUES (?,?,?)").run(id, packet.caseId, JSON.stringify({ id, dateLabel: "Prepared", title, detail, status: "current" })); db.close(); }
}
export const reviewPacketService = new ReviewPacketService();
