import { caseApplicationService } from "@/server/case-application-service";
import { documentApplicationService } from "@/server/document-application-service";
import { verificationService } from "@/server/verification-service";
import { getDatabase } from "@/server/database";
import type { ReviewPacket, TimelineEvent } from "@/types/case";

export class ReviewPacketService {
  async list(caseId: string) { await getDatabase().initialize(); return (await getDatabase().query<{ payload: string }>({ sql: "SELECT payload FROM review_packets WHERE case_id = ?", params: [caseId] })).map((row) => JSON.parse(row.payload) as ReviewPacket).sort((a, b) => a.createdAt.localeCompare(b.createdAt)); }
  async get(caseId: string, packetId: string) { return (await this.list(caseId)).find((packet) => packet.id === packetId) ?? null; }
  async create(caseId: string, verificationResultId: string) { const detail = await caseApplicationService.getCaseDetail(caseId); if (!detail) throw new Error("CASE_NOT_FOUND"); const finding = (await verificationService.run(caseId))?.find((item) => item.id === verificationResultId); if (!finding || finding.outcome !== "POTENTIAL_ISSUE") throw new Error("INELIGIBLE_VERIFICATION_RESULT"); const existing = (await this.list(caseId)).find((packet) => packet.relatedVerificationResultId === finding.id); if (existing) return existing; const parcel = detail.landParcels[0]; const now = new Date().toISOString(); const supportingDocumentIds: string[] = []; for (const id of finding.sourceDocumentIds) if (await documentApplicationService.get(caseId, id)) supportingDocumentIds.push(id); const packet: ReviewPacket = { id: `${caseId}-${finding.id}-packet`, caseId, relatedVerificationResultId: finding.id, issueCategory: finding.ruleId, district: detail.case.location.district, circle: detail.case.location.circle, mauza: detail.case.location.village, khata: parcel?.khata || "", khesra: parcel?.khesra, comparedValues: { expected: finding.expectedValue, observed: finding.observedValue }, supportingDocumentIds, sourceVerificationResultIds: [finding.id], issueSummary: finding.detail, citizenNotes: "", requestedReviewText: "Please review the synthetic records listed in this draft and clarify the difference shown above.", status: "DRAFT", createdAt: now, updatedAt: now }; await this.saveWithTimeline(packet, "Review packet created", "A synthetic review packet draft was created."); return (await this.get(caseId, packet.id))!; }
  async update(caseId: string, packetId: string, input: { citizenNotes?: string; requestedReviewText?: string; status?: "READY_FOR_REVIEW" }) { const packet = await this.get(caseId, packetId); if (!packet) throw new Error("PACKET_NOT_FOUND"); if (packet.status === "READY_FOR_REVIEW") { if (input.citizenNotes !== undefined || input.requestedReviewText !== undefined) throw new Error("PACKET_LOCKED"); return packet; } const next = { ...packet, citizenNotes: input.citizenNotes ?? packet.citizenNotes, requestedReviewText: input.requestedReviewText ?? packet.requestedReviewText, status: input.status === "READY_FOR_REVIEW" ? "READY_FOR_REVIEW" as const : packet.status, updatedAt: new Date().toISOString() }; await this.saveWithTimeline(next, next.status === "READY_FOR_REVIEW" ? "Packet prepared for review" : undefined, "This synthetic packet was marked ready for review; it was not submitted."); return next; }
  private async saveWithTimeline(packet: ReviewPacket, title?: string, detail?: string) { const statements = [{ sql: "INSERT INTO review_packets (id,case_id,payload) VALUES (?,?,?) ON CONFLICT (id) DO UPDATE SET payload = EXCLUDED.payload", params: [packet.id, packet.caseId, JSON.stringify(packet)] }]; if (title) { const id = `${packet.id}-${title.includes("ready") ? "ready" : "created"}`; const event: TimelineEvent = { id, dateLabel: "Prepared", title, detail: detail!, status: "current" }; statements.push({ sql: "INSERT INTO timeline_events (id,case_id,payload) VALUES (?,?,?) ON CONFLICT (id) DO NOTHING", params: [id, packet.caseId, JSON.stringify(event)] }); } await getDatabase().transaction(statements); }
}
export const reviewPacketService = new ReviewPacketService();
