import { DatabaseSync } from "node:sqlite";
import { existsSync } from "node:fs";
import { join } from "node:path";
import { documentApplicationService } from "@/server/document-application-service";
import type { VerificationItem } from "@/types/case";

const dbPath = join(process.cwd(), "data", "bhoomi-check.sqlite");
const normalize = (value: string) => value.toLowerCase().replace(/[\s.,_-]+/g, "").trim();
const area = (text: string) => text.match(/Area:\s*([0-9.]+)\s*acre/i)?.[1];
const holder = (text: string) => text.match(/Recorded holder:\s*(.+)/i)?.[1]?.trim();
export class VerificationService {
  run(caseId: string): VerificationItem[] | null { if (!existsSync(dbPath)) return null; documentApplicationService.ensureSeedDocuments(); const docs = documentApplicationService.list(caseId); if (!docs.length) return null; const historical = docs.find((d) => d.id.endsWith("historical")); const survey = docs.find((d) => d.id.endsWith("survey")); const genealogy = docs.find((d) => d.id.endsWith("genealogy")); const results: VerificationItem[] = [];
    if (!historical || !survey || !area(historical.sourceText) || !area(survey.sourceText)) results.push({ id: `${caseId}-area-evidence`, ruleId: "AREA_CONSISTENCY", outcome: "INSUFFICIENT_EVIDENCE", title: "Area comparison needs more evidence", detail: "Potential area comparison could not be completed because a required synthetic record or area value is missing.", status: "review", confidence: 0, evidence: "INSUFFICIENT_EVIDENCE · Historical and survey records", sourceDocumentIds: [historical?.id, survey?.id].filter((id): id is string => Boolean(id)) });
    else { const expected = area(historical.sourceText)!; const observed = area(survey.sourceText)!; const matches = normalize(expected) === normalize(observed); results.push({ id: `${caseId}-area-consistency`, ruleId: "AREA_CONSISTENCY", outcome: matches ? "PASS" : "POTENTIAL_ISSUE", title: matches ? "Area values are consistent" : "Potential area mismatch", detail: matches ? `Synthetic historical and survey records both show ${expected} acre.` : `Potential area mismatch: historical records show ${expected} acre while the synthetic survey record shows ${observed} acre. This does not decide which value is legally correct.`, status: matches ? "passed" : "warning", confidence: 100, evidence: `Rule AREA_CONSISTENCY · ${historical.title}: ${expected} acre · ${survey.title}: ${observed} acre`, sourceDocumentIds: [historical.id, survey.id], expectedValue: `${expected} acre`, observedValue: `${observed} acre` }); }
    if (!genealogy || !survey) results.push({ id: `${caseId}-family-evidence`, ruleId: "FAMILY_CONTEXT", outcome: "INSUFFICIENT_EVIDENCE", title: "Family-context comparison needs more evidence", detail: "Potential family-context comparison could not be completed because a required synthetic record is missing.", status: "review", confidence: 0, evidence: "INSUFFICIENT_EVIDENCE · Genealogy and survey records", sourceDocumentIds: [genealogy?.id, survey?.id].filter((id): id is string => Boolean(id)) });
    else { const childB = genealogy.sourceText.match(/Synthetic Child B \d+/)?.[0]; const surveyHolder = holder(survey.sourceText) || ""; if (!childB || !surveyHolder) results.push({ id: `${caseId}-family-evidence`, ruleId: "FAMILY_CONTEXT", outcome: "INSUFFICIENT_EVIDENCE", title: "Family-context comparison needs more evidence", detail: "Potential family-context comparison could not be completed because a required synthetic person or holder value is missing.", status: "review", confidence: 0, evidence: "INSUFFICIENT_EVIDENCE · Genealogy member and survey holder", sourceDocumentIds: [genealogy.id, survey.id] }); else { const mismatch = !normalize(surveyHolder).includes(normalize(childB)); results.push({ id: `${caseId}-family-context`, ruleId: "FAMILY_CONTEXT", outcome: mismatch ? "POTENTIAL_ISSUE" : "PASS", title: mismatch ? "Potential family-record inconsistency" : "Family context is consistent", detail: mismatch ? `The genealogy includes ${childB}, while the synthetic survey holder context records ${surveyHolder}. This is an informational consistency check, not an ownership conclusion.` : "The available synthetic genealogy and survey holder context are consistent.", status: mismatch ? "warning" : "passed", confidence: 100, evidence: `Rule FAMILY_CONTEXT · ${genealogy.title}: ${childB} · ${survey.title}: ${surveyHolder}`, sourceDocumentIds: [genealogy.id, survey.id], expectedValue: childB, observedValue: surveyHolder }); } }
    const db = new DatabaseSync(dbPath); db.prepare("DELETE FROM verification_results WHERE case_id = ?").run(caseId); for (const item of results) db.prepare("INSERT INTO verification_results (id,case_id,payload) VALUES (?,?,?)").run(item.id, caseId, JSON.stringify(item)); db.close(); return results; }
  list(caseId: string) { if (!existsSync(dbPath)) return []; const db = new DatabaseSync(dbPath); const rows = db.prepare("SELECT payload FROM verification_results WHERE case_id = ?").all(caseId) as { payload: string }[]; db.close(); return rows.map((row) => JSON.parse(row.payload) as VerificationItem); }
}
export const verificationService = new VerificationService();
