import { describe, expect, it } from "vitest";
import { parseSupportedArea, verificationService } from "@/server/verification-service";
import type { DocumentItem, DocumentKind } from "@/types/case";

const document = (id: string, kind: DocumentKind, sourceText: string): DocumentItem => ({ id, title: id, kind, type: "Synthetic test record", addedLabel: "Synthetic test", state: "extracted", fields: [], sourceText, isSynthetic: true });
const comparisonDocuments = ({ historical = "Area: 1.20 acre", survey = "Area: 1.20 acre\nRecorded holder: Example Person", genealogy = "Family member under review: Example Person" }: { historical?: string; survey?: string; genealogy?: string } = {}) => [document("case-historical", "legacy-record", historical), document("case-survey", "survey-record", survey), document("case-genealogy", "family-note", genealogy)];
const result = (documents: DocumentItem[], ruleId: "AREA_CONSISTENCY" | "FAMILY_CONTEXT") => verificationService.evaluateDocuments("case", documents).find((item) => item.ruleId === ruleId)!;

describe("deterministic verification", () => {
  it("finds hero area and family-context potential discrepancies with source traceability", async () => { const results = (await verificationService.run("demo-family-001"))!; const area = results.find((item) => item.ruleId === "AREA_CONSISTENCY"); const family = results.find((item) => item.ruleId === "FAMILY_CONTEXT"); expect(area).toMatchObject({ outcome: "POTENTIAL_ISSUE", status: "warning", expectedValue: "1.20 acre", observedValue: "1.02 acre" }); expect(area?.sourceDocumentIds).toEqual(["demo-family-001-historical", "demo-family-001-survey"]); expect(family).toMatchObject({ outcome: "POTENTIAL_ISSUE", status: "warning", expectedValue: "Synthetic Child B 001", observedValue: "Synthetic Child A 001" }); });
  it("keeps the control case free of hero potential discrepancies with an area pass and missing family evidence", async () => { const results = (await verificationService.run("demo-family-002"))!; expect(results.some((item) => item.outcome === "POTENTIAL_ISSUE")).toBe(false); expect(results.find((item) => item.ruleId === "AREA_CONSISTENCY")?.outcome).toBe("PASS"); expect(results.find((item) => item.ruleId === "FAMILY_CONTEXT")?.outcome).toBe("INSUFFICIENT_EVIDENCE"); });
  it("treats supported numeric equivalents as a pass and malformed or unsupported areas as insufficient evidence", async () => { expect(result(comparisonDocuments({ historical: "Area: 1.20 acre", survey: "Area: 1.200 acre\nRecorded holder: Example Person" }), "AREA_CONSISTENCY").outcome).toBe("PASS"); for (const historical of ["Area: 1.2.0 acre", "Area: NaN acre", "Area: Infinity acre", "Area: 1.20 hectare", "Area:"]) expect(result(comparisonDocuments({ historical }), "AREA_CONSISTENCY").outcome).toBe("INSUFFICIENT_EVIDENCE"); expect(result(comparisonDocuments({ historical: "No recorded area" }), "AREA_CONSISTENCY").outcome).toBe("INSUFFICIENT_EVIDENCE"); });
  it("uses a generic structured family comparison subject with safe normalization", async () => { expect(result(comparisonDocuments({ genealogy: "Family member under review: Demo Person-B, 44", survey: "Area: 1.20 acre\nRecorded holder:  demo person b 44 " }), "FAMILY_CONTEXT").outcome).toBe("PASS"); expect(result(comparisonDocuments({ genealogy: "Family member under review: Demo Person B 44", survey: "Area: 1.20 acre\nRecorded holder: Demo Person A 44" }), "FAMILY_CONTEXT").outcome).toBe("POTENTIAL_ISSUE"); expect(result(comparisonDocuments({ genealogy: "Synthetic Parent → Synthetic Child", survey: "Area: 1.20 acre\nRecorded holder: Synthetic Child" }), "FAMILY_CONTEXT").outcome).toBe("INSUFFICIENT_EVIDENCE"); });
  it("parses only one supported labelled acre area", async () => { expect(parseSupportedArea("Area: 1.20 acre")).toEqual({ value: 1.2, unit: "acre", display: "1.20 acre" }); expect(parseSupportedArea("Area: 1.20 acre\nArea: 1.20 acre")).toBeNull(); });
  it("is deterministic and persists results", async () => { const first = await verificationService.run("demo-family-001"); expect(await verificationService.run("demo-family-001")).toEqual(first); expect(await verificationService.list("demo-family-001")).toEqual(first); });
});
