"use client";
import Link from "next/link";
import { CasePage } from "@/components/case-page";
import { CaseHeader, CaseNavigation } from "@/components/shell";
import { CaseProgress, DocumentCard, NextActionCard, VerificationIssue, VerificationSummary } from "@/components/domain";
import { t } from "@/lib/i18n";

export default function Dashboard() {
  return <CasePage>{(detail, caseId) => {
    const parcel = detail.landParcels[0];
    const potentialIssues = detail.verification.filter((item) => item.outcome === "POTENTIAL_ISSUE");
    const readyPacket = detail.reviewPackets?.find((packet) => packet.status === "READY_FOR_REVIEW");
    const recommendedGuidance = detail.guidance?.find((item) => item.status === "READY_TO_REVIEW") ?? detail.guidance?.[0];
    const c = t().verification;
    return <main id="main" className="case-layout"><CaseNavigation caseId={caseId} /><div className="case-content"><CaseHeader title={detail.case.nickname} subtitle={`${detail.case.location.village} · Khata ${parcel?.khata || "Not added"}${parcel?.khesra ? ` · Khesra ${parcel.khesra}` : ""}`} /><CaseProgress {...detail.case.progress} /><section className="dashboard-grid"><article className="summary-card"><p className="eyebrow">Survey stage</p><h2>{detail.case.surveyStage}</h2><p>Review the record before selecting any next action.</p><Link className="text-link" href={`/cases/${caseId}/survey-record`}>Open survey record →</Link></article><article className="summary-card"><p className="eyebrow">Land summary</p><h2>{parcel ? `${parcel.area.value} ${parcel.area.unit}` : "No parcel yet"}</h2><p>{parcel ? `Khata ${parcel.khata} · Khesra ${parcel.khesra || "Not added"}` : "Add land information when ready."}</p><Link className="text-link" href={`/cases/${caseId}/survey-record`}>See recorded details →</Link></article><article className="summary-card"><p className="eyebrow">Family summary</p><h2>{detail.family.members.length} people noted</h2><p>{detail.family.members.length ? "Relationships are available to review." : "No family information added yet."}</p><Link className="text-link" href={`/cases/${caseId}/family`}>View family information →</Link></article></section>{detail.verification.length > 0 && <section className="dashboard-verification"><VerificationSummary items={detail.verification} compact /><Link href={`/cases/${caseId}/verification`} className="text-link">{c.overviewLink} <span aria-hidden>→</span></Link></section>}{recommendedGuidance && <section className="dashboard-next-action"><p className="eyebrow">Prepare next</p><h2>{potentialIssues.length ? `${potentialIssues.length} possible difference${potentialIssues.length === 1 ? "" : "s"} to review` : "Continue preparing your record references"}</h2><NextActionCard emphasis href={`/cases/${caseId}/next-action`} title={recommendedGuidance.title} detail={recommendedGuidance.explanation} /></section>}<section className="section-head"><div><p className="eyebrow">Potential issues</p><h2>{potentialIssues.length ? `${potentialIssues.length} items need your attention` : "No possible differences found"}</h2></div><Link href={`/cases/${caseId}/verification`} className="text-link">View all checks →</Link></section><div className="issue-list">{potentialIssues.map((item) => <VerificationIssue key={item.id} item={item} />)}</div><section className="section-head"><div><p className="eyebrow">Documents</p><h2>Your records in one place</h2></div><Link href={`/cases/${caseId}/documents`} className="text-link">View all →</Link></section><div className="document-list">{detail.documents.slice(0, 2).map((document) => <DocumentCard document={document} key={document.id} href={`/cases/${caseId}/documents`} />)}</div></div></main>;
  }}</CasePage>;
}
