"use client";
import Link from "next/link";
import { CasePage } from "@/components/case-page";
import { CaseHeader, CaseNavigation } from "@/components/shell";
import { CaseProgress, DocumentCard, NextActionCard, VerificationIssue, VerificationSummary } from "@/components/domain";
import { useTranslation } from "@/components/locale-context";

export default function Dashboard() {
  const c = useTranslation();
  return <CasePage>{(detail, caseId) => {
    const parcel = detail.landParcels[0];
    const potentialIssues = detail.verification.filter((item) => item.outcome === "POTENTIAL_ISSUE");
    const readyPacket = detail.reviewPackets?.find((packet) => packet.status === "READY_FOR_REVIEW");
    const recommendedGuidance = detail.guidance?.find((item) => item.status === "READY_TO_REVIEW") ?? detail.guidance?.[0];
    return <main id="main" className="case-layout"><CaseNavigation caseId={caseId} /><div className="case-content"><CaseHeader title={detail.case.nickname} subtitle={`${detail.case.location.village} · Khata ${parcel?.khata || c.common.notAdded}${parcel?.khesra ? ` · Khesra ${parcel.khesra}` : ""}`} /><CaseProgress {...detail.case.progress} /><section className="dashboard-grid"><article className="summary-card"><p className="eyebrow">{c.dashboard.surveyStage}</p><h2>{detail.case.surveyStage}</h2><p>{c.dashboard.surveyDetail}</p><Link className="text-link" href={`/cases/${caseId}/survey-record`}>{c.dashboard.openSurvey} →</Link></article><article className="summary-card"><p className="eyebrow">{c.dashboard.landSummary}</p><h2>{parcel ? `${parcel.area.value} ${parcel.area.unit}` : c.dashboard.noParcel}</h2><p>{parcel ? `Khata ${parcel.khata} · Khesra ${parcel.khesra || c.common.notAdded}` : c.dashboard.addLand}</p><Link className="text-link" href={`/cases/${caseId}/survey-record`}>{c.dashboard.recordedDetails} →</Link></article><article className="summary-card"><p className="eyebrow">{c.dashboard.familySummary}</p><h2>{detail.family.members.length} {c.dashboard.peopleNoted}</h2><p>{detail.family.members.length ? c.dashboard.familyAvailable : c.dashboard.noFamily}</p><Link className="text-link" href={`/cases/${caseId}/family`}>{c.dashboard.viewFamily} →</Link></article></section>{detail.verification.length > 0 && <section className="dashboard-verification"><VerificationSummary items={detail.verification} compact /><Link href={`/cases/${caseId}/verification`} className="text-link">{c.verification.overviewLink} <span aria-hidden>→</span></Link></section>}{recommendedGuidance && <section className="dashboard-next-action"><p className="eyebrow">{c.dashboard.prepareNext}</p><h2>{potentialIssues.length ? `${potentialIssues.length} ${c.dashboard.differences}` : c.dashboard.continuePreparing}</h2><NextActionCard emphasis href={`/cases/${caseId}/next-action`} title={recommendedGuidance.title} detail={recommendedGuidance.explanation} /></section>}<section className="section-head"><div><p className="eyebrow">{c.dashboard.potentialIssues}</p><h2>{potentialIssues.length ? `${potentialIssues.length} ${c.dashboard.needAttention}` : c.dashboard.noDifferences}</h2></div><Link href={`/cases/${caseId}/verification`} className="text-link">{c.dashboard.allChecks} →</Link></section><div className="issue-list">{potentialIssues.map((item) => <VerificationIssue key={item.id} item={item} />)}</div><section className="section-head"><div><p className="eyebrow">{c.dashboard.documents}</p><h2>{c.dashboard.recordsPlace}</h2></div><Link href={`/cases/${caseId}/documents`} className="text-link">{c.dashboard.viewAll} →</Link></section><div className="document-list">{detail.documents.slice(0, 2).map((document) => <DocumentCard document={document} key={document.id} href={`/cases/${caseId}/documents`} />)}</div></div></main>;
  }}</CasePage>;
}
