export type DocumentProcessingStatus = "not-started" | "processing" | "extracted" | "failed";
export type DocumentKind = "legacy-record" | "family-note" | "survey-record";
export type VerificationStatus = "passed" | "warning" | "review";
export type TimelineStatus = "done" | "current" | "upcoming";

export type CaseLocation = { district: string; circle: string; village: string };
export type LandCase = { id: string; nickname: string; location: CaseLocation; surveyStage: string; progress: { done: number; total: number } };
export type LandParcel = { id: string; label: string; khata: string; khesra?: string; area: { value: number; unit: "acres" } };
export type FamilyMember = { id: string; name: string; role: string; note: string };
export type FamilyRelationship = { id: string; fromMemberId: string; toMemberId: string; label: string };
export type ExtractedField = { id: string; label: string; value: string; confidence: number; source: string };
export type ExtractionConfidence = "low" | "medium" | "high";
export type ExtractionFactKey = "documentType" | "personName" | "relationship" | "khata" | "khesra" | "recordedArea" | "areaUnit" | "location" | "surveyReference" | "recordDate";
export type ExtractionEvidence = { quote: string; start: number; end: number };
export type ExtractionFact = { key: ExtractionFactKey; value: string; confidence: ExtractionConfidence; evidence: ExtractionEvidence; needsHumanReview: boolean; uncertainty?: string };
export type ExtractedDocument = { documentType?: string; facts: ExtractionFact[] };
export type DocumentExtraction = { id: string; caseId: string; documentId: string; status: "completed" | "failed"; result?: ExtractedDocument; provider?: string; model?: string; promptVersion?: string; createdAt: string; error?: { code: string; message: string } };
export type DocumentItem = { id: string; title: string; kind: DocumentKind; type: string; addedLabel: string; state: DocumentProcessingStatus; fields: ExtractedField[]; sourceText: string; isSynthetic: true };
export type SyntheticDocumentFixture = { id: string; title: string; kind: DocumentKind; type: string; sourceText: string; isSynthetic: true };
export type VerificationOutcome = "PASS" | "POTENTIAL_ISSUE" | "INSUFFICIENT_EVIDENCE";
export type VerificationRuleId = "AREA_CONSISTENCY" | "FAMILY_CONTEXT";
export type VerificationItem = {
  id: string;
  ruleId: VerificationRuleId;
  outcome: VerificationOutcome;
  title: string;
  detail: string;
  status: VerificationStatus;
  confidence: number;
  evidence: string;
  sourceDocumentIds: string[];
  expectedValue?: string;
  observedValue?: string;
};
export type SurveyRecord = { recordedName: string; khata: string; khesra?: string; area: { value: number; unit: "acres" }; surveyStage: string; mapReference: string };
export type GuidanceAction = { id: string; title: string; detail: string };
export type NextAction = { recommendedTitle: string; recommendedDetail: string; steps: string[]; options: GuidanceAction[] };
export type GuidanceStatus = "READY_TO_REVIEW" | "NEEDS_MORE_INFORMATION" | "NO_ACTION_NEEDED";
export type GuidanceChecklistItem = { id: string; label: string };
export type GuidanceItem = { id: string; caseId: string; verificationResultId: string; ruleId: VerificationRuleId; title: string; explanation: string; priority: number; status: GuidanceStatus; documentIds: string[]; checklist: GuidanceChecklistItem[]; caution: string; sourceVerificationResultIds: string[] };
export type ReviewPacketStatus = "DRAFT" | "READY_FOR_REVIEW";
export type ReviewPacket = { id: string; caseId: string; relatedVerificationResultId: string; issueCategory: VerificationRuleId; district: string; circle: string; mauza: string; khata: string; khesra?: string; comparedValues: { expected?: string; observed?: string }; supportingDocumentIds: string[]; sourceVerificationResultIds: string[]; issueSummary: string; citizenNotes: string; requestedReviewText: string; status: ReviewPacketStatus; createdAt: string; updatedAt: string };
export type TimelineEvent = { id: string; dateLabel: string; title: string; detail: string; status: TimelineStatus };
export type GovernmentProcessContext = { source: "MOCK_GOVERNMENT_ADAPTER"; synthetic: true; status: { stageId: string; stage: string }; availableActions: string[]; disclaimer: string };
export type CaseDetail = { case: LandCase; family: { members: FamilyMember[]; relationships: FamilyRelationship[] }; landParcels: LandParcel[]; documents: DocumentItem[]; surveyRecord?: SurveyRecord; verification: VerificationItem[]; guidance?: GuidanceItem[]; reviewPackets?: ReviewPacket[]; governmentProcess?: GovernmentProcessContext; nextAction?: NextAction; timeline: TimelineEvent[] };

export type OfficialParcelSearchQuery = { district: string; circle: string; mauza: string; khataNumber?: string; khesraNumber?: string };
export type OfficialIdentityMatch = "EXACT_MATCH" | "PARTIAL_MATCH" | "MISMATCH";
export type OfficialParcelRecord = { id: string; sourceProvider: "synthetic"; provenance: "SYNTHETIC_OFFICIAL_FIXTURE"; sourceReference: string; parcelIdentity: Required<OfficialParcelSearchQuery>; recordData: { recordedArea: number; recordedAreaUnit: "acre"; normalizedAreaAcres: number; holderNames: string[]; recordType: string; surveyStage: string; remarks: string }; sourceMetadata: { retrievedAt: string; displayName: string; syntheticNotice: string; authoritative: false } };
export type ImportedOfficialRecord = { id: string; caseId: string; officialRecordId: string; provider: "synthetic"; provenance: "SYNTHETIC_OFFICIAL_FIXTURE"; sourceReference: string; identityMatch: OfficialIdentityMatch; record: OfficialParcelRecord; importedAt: string };
