"use client";
import { createContext, useContext, useEffect, useState, type ReactNode } from "react";
import { caseService, type CreateCaseInput } from "@/services/case-service";
import type { CaseDetail, SyntheticDocumentFixture } from "@/types/case";
import { resolveCaseRoute } from "@/lib/case-route";
import { useLocale } from "@/components/locale-context";
import type { Locale } from "@/lib/i18n";
type CaseState = { status: "loading" } | { status: "ready"; detail: CaseDetail; locale: Locale } | { status: "not-found" } | { status: "error"; message: string };
const CaseContext = createContext<{ cases: Record<string, CaseState | undefined>; loadCase: (caseId: string) => Promise<void>; createCase: (input: CreateCaseInput) => Promise<CaseDetail>; listFixtures: (caseId: string) => Promise<SyntheticDocumentFixture[]>; attachFixture: (caseId: string, fixtureId: string) => Promise<void>; processDocument: (caseId: string, documentId: string) => Promise<void> } | null>(null);
export function CaseProvider({ children }: { children: ReactNode }) { const [cases, setCases] = useState<Record<string, CaseState | undefined>>({}); const { locale } = useLocale(); const save = (detail: CaseDetail | null) => { if (detail) setCases((current) => ({ ...current, [detail.case.id]: { status: "ready", detail, locale } })); }; const loadCase = async (caseId: string) => { setCases((current) => ({ ...current, [caseId]: { status: "loading" } })); const state = await resolveCaseRoute(caseId, caseService, locale); setCases((current) => ({ ...current, [caseId]: state.status === "ready" ? { ...state, locale } : state })); }; const createCase = async (input: CreateCaseInput) => { const detail = await caseService.createCase(input); save(detail); return detail; }; const attachFixture = async (caseId: string, fixtureId: string) => save(await caseService.attachDocumentFixture(caseId, fixtureId)); const processDocument = async (caseId: string, documentId: string) => save(await caseService.processDocument(caseId, documentId)); return <CaseContext.Provider value={{ cases, loadCase, createCase, listFixtures: (caseId) => caseService.listDocumentFixtures(caseId), attachFixture, processDocument }}>{children}</CaseContext.Provider>; }
export const shouldLoadCase = (state: CaseState | undefined, locale: Locale) => !state || (state.status === "ready" && state.locale !== locale);
export function useCaseDetail(caseId: string) { const value = useContext(CaseContext); const { locale } = useLocale(); if (!value) throw new Error("useCaseDetail must be used inside CaseProvider"); const state = value.cases[caseId]; useEffect(() => { if (shouldLoadCase(state, locale)) void value.loadCase(caseId); }, [caseId, locale, state, value]); return state ?? { status: "loading" as const }; }
export function useCaseActions() { const value = useContext(CaseContext); if (!value) throw new Error("useCaseActions must be used inside CaseProvider"); return { createCase: value.createCase, listFixtures: value.listFixtures, attachFixture: value.attachFixture, processDocument: value.processDocument }; }
