import Link from "next/link";
import type { DocumentItem, SurveyRecord, TimelineEvent, VerificationItem } from "@/types/case";
import { t } from "@/lib/i18n";
import { outcomePresentation, sourcesForVerification, summarizeVerification } from "@/lib/verification-presentation";
export function ConfidenceBadge({ value }: { value: number }) { return <span className={value >= 95 ? "confidence high" : "confidence"}>{value}% confidence</span>; }
export function CaseProgress({ done = 3, total = 5 }: { done?: number; total?: number }) { return <section className="progress" aria-label={`Case progress: ${done} of ${total} steps complete`}><div><strong>{done} of {total} steps complete</strong><span> You are making steady progress.</span></div><div className="track"><i style={{ width: `${(done / total) * 100}%` }} /></div></section> }
export function DocumentCard({ document, href }: { document: DocumentItem; href?: string }) { return <article className="document-card"><div className="document-icon" aria-hidden>▤</div><div><p className="eyebrow">{document.type}</p><h3>{document.title}</h3><p>{document.addedLabel} · <span className="status ready">Extracted</span></p></div>{href && <Link className="text-link" href={href}>Inspect fields <span aria-hidden>→</span></Link>}</article> }
export function FamilyMemberCard({ name, role, note }: { name: string; role: string; note: string }) { return <article className="family-card"><div className="avatar" aria-hidden>{name.slice(0, 1)}</div><div><h3>{name}</h3><p><strong>{role}</strong> · {note}</p></div></article> }
export function VerificationSummary({ items, compact = false }: { items: VerificationItem[]; compact?: boolean }) { const c = t().verification; const summary = summarizeVerification(items); return <section className={`verification-summary ${compact ? "compact" : ""}`} aria-labelledby="verification-summary-title"><div><p className="eyebrow">{c.summaryTitle}</p><h2 id="verification-summary-title">{summary.POTENTIAL_ISSUE ? c.potentialIssue : summary.INSUFFICIENT_EVIDENCE && !summary.PASS ? c.insufficientEvidence : c.passed}</h2><p>{summary.POTENTIAL_ISSUE ? c.potentialIssueDetail : summary.INSUFFICIENT_EVIDENCE && !summary.PASS ? c.insufficientEvidenceDetail : c.passDetail}</p></div><ul className="verification-counts" aria-label="Verification result counts"><li className="warning"><strong>{summary.POTENTIAL_ISSUE}</strong><span>{c.potentialIssue}</span></li><li className="passed"><strong>{summary.PASS}</strong><span>{c.passed}</span></li><li className="review"><strong>{summary.INSUFFICIENT_EVIDENCE}</strong><span>{c.insufficientEvidence}</span></li></ul></section> }
export function VerificationIssue({ item }: { item: VerificationItem }) { const c = t().verification; const presentation = outcomePresentation(item.outcome); return <article className={`issue ${presentation.className}`}><div className="issue-symbol" aria-hidden>{presentation.symbol}</div><div><p className="status-label"><strong>{c[presentation.labelKey]}</strong></p><h3>{item.title}</h3><p>{item.detail}</p><p className="evidence"><strong>{t().labels.evidence}:</strong> {item.evidence} · <ConfidenceBadge value={item.confidence} /></p></div></article> }
export function VerificationDiscrepancyCard({ item, documents }: { item: VerificationItem; documents: DocumentItem[] }) { const c = t().verification; const sources = sourcesForVerification(item, documents); const [firstSource, secondSource] = sources; return <article className="discrepancy-card" aria-labelledby={`${item.id}-title`}><div className="discrepancy-heading"><div><p className="eyebrow">{c.potentialIssue} · {item.ruleId.replace(/_/g, " ")}</p><h2 id={`${item.id}-title`}>{item.title}</h2></div><span className="status-pill warning">! {c.potentialIssue}</span></div><p>{item.detail}</p><section aria-labelledby={`${item.id}-records`}><h3 id={`${item.id}-records`}>{c.comparedRecords}</h3><div className="evidence-comparison"><div><p className="eyebrow">{c.recordA}</p><strong>{item.expectedValue || c.notAvailable}</strong><p><b>{c.source}:</b> {firstSource?.label || c.notAvailable}</p><p className="micro">{firstSource ? `${firstSource.type} · ${firstSource.id}` : c.notAvailable}</p></div><div><p className="eyebrow">{c.recordB}</p><strong>{item.observedValue || c.notAvailable}</strong><p><b>{c.source}:</b> {secondSource?.label || c.notAvailable}</p><p className="micro">{secondSource ? `${secondSource.type} · ${secondSource.id}` : c.notAvailable}</p></div></div></section><section className="why-flagged" aria-labelledby={`${item.id}-why`}><h3 id={`${item.id}-why`}>{c.whyFlagged}</h3><p>{item.evidence}</p></section><aside className="verification-caution"><strong>{c.caution}</strong><p>{c.cautionDetail}</p></aside></article> }
export function SurveyRecordCard({ record }: { record: SurveyRecord }) { return <article className="survey-card"><div className="card-label">Synthetic Khanapuri Parcha</div><dl><div><dt>Recorded name</dt><dd>{record.recordedName}</dd></div><div><dt>Khata / Khesra</dt><dd>{record.khata} / {record.khesra || "Not added"}</dd></div><div><dt>Recorded area</dt><dd>{record.area.value} {record.area.unit}</dd></div><div><dt>Survey stage</dt><dd>{record.surveyStage}</dd></div><div><dt>Map reference</dt><dd>{record.mapReference}</dd></div></dl></article> }
export function NextActionCard({ title, detail, href, emphasis = false }: { title: string; detail: string; href: string; emphasis?: boolean }) { return <Link href={href} className={`action-card ${emphasis ? "emphasis" : ""}`}><div><h3>{title}</h3><p>{detail}</p></div><span aria-hidden>→</span></Link> }
export function Timeline({ events }: { events: TimelineEvent[] }) { return <ol className="timeline">{events.map((event) => <li key={event.id} className={event.status}><span aria-hidden /><div><p className="eyebrow">{event.dateLabel}</p><h3>{event.title}</h3><p>{event.detail}</p></div></li>)}</ol> }
export function LoadingState() { return <div className="state"><span className="spinner" aria-hidden />{t().caseStates.loading}</div> }
export function EmptyState({ title, detail, action }: { title: string; detail: string; action?: React.ReactNode }) { return <div className="state empty"><h2>{title}</h2><p>{detail}</p>{action}</div> }
export function ErrorState() { const c = t().caseStates; return <div className="state error" role="alert"><h2>{c.errorTitle}</h2><p>{c.errorDetail}</p><button onClick={() => window.location.reload()}>{c.retry}</button></div> }
