"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useLocale, useTranslation } from "@/components/locale-context";
const defaultCaseId = "demo-family-001";
export function SiteHeader() { const c = useTranslation(); const { locale, setLocale } = useLocale(); return <><a className="skip" href="#main">{c.labels.skip}</a><header className="site-header"><Link href="/" className="brand" aria-label={c.labels.homeLabel}><span className="brand-mark" aria-hidden>⌂</span><span>Bhoomi<span>Check</span></span></Link><nav aria-label={c.labels.primaryNav}><button type="button" className="locale-switch" aria-label={c.labels.chooseLanguage} aria-pressed={locale === "hi"} onClick={() => setLocale(locale === "en" ? "hi" : "en")}>{locale === "en" ? "हिंदी" : "English"}</button><Link href={`/cases/${defaultCaseId}`}>{c.nav.dashboard}</Link><Link className="button small" href="/create-case">{c.cta.check}</Link></nav></header></> }
export function CaseNavigation({ caseId }: { caseId: string }) { const pathname = usePathname(); const c = useTranslation(); const links = [ ["dashboard", `/cases/${caseId}`], ["documents", `/cases/${caseId}/documents`], ["family", `/cases/${caseId}/family`], ["verification", `/cases/${caseId}/verification`], ["survey", `/cases/${caseId}/survey-record`], ["parcel", `/cases/${caseId}/parcel-intelligence`], ["action", `/cases/${caseId}/next-action`], ["timeline", `/cases/${caseId}/timeline`] ] as const; return <nav className="case-nav" aria-label={c.labels.caseNav}>{links.map(([key, href]) => <Link key={key} className={pathname === href ? "active" : ""} href={href}>{c.nav[key]}</Link>)}</nav> }
export function Notice() { return <p className="notice" role="note">{useTranslation().notice}</p> }
export function SiteFooter() { return <footer>{useTranslation().footer}</footer> }
export function CaseHeader({ title, subtitle }: { title: string; subtitle: string }) { return <header className="case-header"><p className="eyebrow">{useTranslation().labels.caseHeader}</p><h1>{title}</h1><p>{subtitle}</p></header> }
