"use client";
import Link from "next/link";
import { CasePage } from "@/components/case-page";
import { CaseHeader, CaseNavigation } from "@/components/shell";
import { EmptyState, SurveyRecordCard, VerificationDiscrepancyCard } from "@/components/domain";
import { useTranslation } from "@/components/locale-context";
import { useLocale } from "@/components/locale-context";
import { localizedParcelComparisonPresentation } from "@/lib/i18n";
export default function SurveyPage() { const c = useTranslation(); const { locale } = useLocale(); const parcel = localizedParcelComparisonPresentation(locale); return <CasePage>{(detail, caseId) => { const record = detail.surveyRecord; const issues = detail.verification.filter((item) => item.outcome === "POTENTIAL_ISSUE"); if (!record) return <main id="main" className="case-layout"><CaseNavigation caseId={caseId} /><div className="case-content"><CaseHeader title={c.survey.header} subtitle={c.survey.subtitle} /><EmptyState title={c.survey.emptyTitle} detail={c.survey.emptyDetail} /></div></main>; return <main id="main" className="case-layout"><CaseNavigation caseId={caseId} /><div className="case-content"><CaseHeader title={c.survey.recordTitle} subtitle={c.survey.recordDetail} /><SurveyRecordCard record={record} /><section className="callout"><strong>{c.survey.recordTitle}</strong><p>{record.recordedName}, Khata {record.khata}, Khesra {record.khesra || c.labels.notAvailable}, {record.area.value} {record.area.unit}. {c.survey.recordDetail}</p></section><div className="actions"><Link className="button secondary" href={`/cases/${caseId}/parcel-intelligence`}>{parcel.areaComparison}</Link></div><section className="all-checks"><div className="section-head"><div><p className="eyebrow">{c.survey.compare}</p><h2>{c.survey.comparisonFound}</h2></div></div>{issues.length ? issues.map((item) => <div key={item.id}><VerificationDiscrepancyCard item={item} documents={detail.documents} /><Link className="button" href={`/cases/${caseId}/review-packet?result=${encodeURIComponent(item.id)}`}>{c.cta.preparePacket}</Link></div>) : <EmptyState title={c.survey.noDifferences} detail={c.survey.noDifferencesDetail} />}</section><div className="actions"><Link className="button secondary" href={`/cases/${caseId}/next-action`}>{c.survey.reviewNext}</Link><Link className="button secondary" href={`/cases/${caseId}/verification`}>{c.survey.reviewEvidence}</Link></div></div></main>; }}</CasePage>; }
