"use client";
import { useEffect, useState } from "react";
import { CasePage } from "@/components/case-page";
import { useCaseActions } from "@/components/case-context";
import { CaseHeader, CaseNavigation } from "@/components/shell";
import { ConfidenceBadge, DocumentCard, EmptyState } from "@/components/domain";
import type { SyntheticDocumentFixture } from "@/types/case";

export default function DocumentsPage() { const [selected, setSelected] = useState<string | null>(null); const [fixtures, setFixtures] = useState<SyntheticDocumentFixture[]>([]); const { listFixtures, attachFixture, processDocument } = useCaseActions(); useEffect(() => { void listFixtures().then(setFixtures); }, [listFixtures]); return <CasePage>{(detail, caseId) => { const item = detail.documents.find((document) => document.id === selected); return <main id="main" className="case-layout"><CaseNavigation caseId={caseId} /><div className="case-content"><CaseHeader title="Your documents" subtitle="Use only the bundled synthetic fixtures in this prototype." /><section className="fixture-panel"><p className="eyebrow">Add a synthetic document</p><h2>Choose a demo record to add</h2><div className="fixture-list">{fixtures.map((fixture) => <button key={fixture.id} type="button" className="button secondary" disabled={detail.documents.some((document) => document.kind === fixture.kind)} onClick={() => void attachFixture(caseId, fixture.id)}>{fixture.title}</button>)}</div><p className="micro">Synthetic fixtures only. No real documents are accepted or sent anywhere.</p></section><div className="document-list">{detail.documents.length ? detail.documents.map((document) => <article key={document.id} className="document-workflow"><button type="button" className="document-select" style={{ display: "block", width: "100%", padding: 0, border: 0, background: "transparent", textAlign: "left" }} aria-expanded={selected === document.id} aria-controls={selected === document.id ? "extracted-fields" : undefined} onClick={() => setSelected(document.id)}><DocumentCard document={document} /></button><div className="document-actions"><span className={`status ${document.state}`}>{document.state === "extracted" ? "Extracted" : "Ready to process"}</span>{document.state !== "extracted" && <button type="button" className="button small" onClick={() => void processDocument(caseId, document.id)}>Extract fields</button>}</div></article>) : <EmptyState title="No documents added" detail="Choose a synthetic fixture above to start." />}</div>{item && <section id="extracted-fields" className="inspect" aria-live="polite"><div className="section-head"><div><p className="eyebrow">Synthetic source text</p><h2>{item.title}</h2></div><button className="button secondary" onClick={() => setSelected(null)}>Close</button></div><pre className="source-text">{item.sourceText}</pre><p className="eyebrow">Extracted fields</p>{item.fields.length ? item.fields.map((field) => <div className="field-row" key={field.id}><span>{field.label}</span><strong>{field.value}</strong><span><ConfidenceBadge value={field.confidence} /> · {field.source}</span></div>) : <p>Choose “Extract fields” to process this synthetic document.</p>}</section>}</div></main>; }}</CasePage>; }
